version = 1
SPDX-PackageName = "parallel"
SPDX-PackageSupplier = "Ole Tange, http://ole.tange.dk"
SPDX-PackageDownloadLocation = "https://git.savannah.gnu.org/git/parallel.git"

[[annotations]]
path = ["testsuite/input-files/testdir.tar.bz2",
	"testsuite/input-files/random_dirs_no_newline.tar.bz2",
	"testsuite/input-files/random_dirs_with_newline.tar.bz2",
	"testsuite/input-files/testdir/**",
	"testsuite/wanted-results/**",
	"testsuite/testdir/**",
	"packager/obs/**",
	"src/optional/**",
	"packager/debian/debian-template/**",
	"configure",
	"configure.ac",
	"config.h.in",
	"aclocal.m4",
	"install-sh",
	"missing",
	]
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2026 Ole Tange, http://ole.tange.dk and Free Software Foundation, Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["doc/citation-notice-faq.txt", "CREDITS", "NEWS", "README", "src/parallel_cheat_bw.fodt", "packager/debian/README", "doc/parallel**directive", "doc/screenshot.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2026 Ole Tange, http://ole.tange.dk and Free Software Foundation, Inc."
SPDX-License-Identifier = "GFDL-1.3-or-later"

[[annotations]]
path = "packager/0install/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2010-2021 Tim Cuthbertson <tim3d.junk@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["testsuite/input-files/perl-v5.14.2/**", "testsuite/input-files/perllib/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Perl is Copyright (C) 1993-2010 by Larry Wall and others."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "testsuite/input-files/xargs-inputs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) 1998-2022 Free Software Foundation, Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"
